import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    pkg_share = get_package_share_directory('odin_ros_driver_rev1')
    default_rviz = os.path.join(pkg_share, 'rviz', 'driver_view_ros2.rviz')

    # Ports are auto-generated by SDK, no need to configure them
    device_sn = LaunchConfiguration('device_sn')
    start_rviz = LaunchConfiguration('start_rviz')
    rviz_config = LaunchConfiguration('rviz_config')
    # Image resolution: 0 = use first capability from device
    image_width = LaunchConfiguration('image_width')
    image_height = LaunchConfiguration('image_height')
    image_fps = LaunchConfiguration('image_fps')
    image_format = LaunchConfiguration('image_format')

    driver_params = {
        'device_sn': device_sn,
        'operating_mode': 'normal',
        'image_width': image_width,
        'image_height': image_height,
        'image_fps': image_fps,
        'image_format': image_format,
        'raw_frame_id': 'odom',
        'slam_frame_id': 'odom',
        'imu_frame_id': 'odom',
        'image_frame_id': 'odom',
        'image2_frame_id': 'odom',
        'gray_image_frame_id': 'odom',
        'odom_frame_id': 'odom',
        'odom_child_frame_id': 'base_link',
    }

    nodes = [
        Node(
            package='odin_ros_driver_rev1',
            executable='odin_ros_driver_node',
            output='screen',
            parameters=[driver_params],
        ),
        # Node(
        #     package='image_transport',
        #     executable='republish',
        #     name='odin_image_republish',
        #     arguments=[
        #         'compressed',
        #         'raw',
        #         '--ros-args',
        #         '--remap', 'in/compressed:=/odin/image/compressed',
        #         '--remap', 'out:=/odin/image_raw',
        #     ],
        #     output='screen',
        #     condition=IfCondition(start_rviz),
        # ),
        # --- NEW: cloudrender with YAML under src/ ---
        Node(
            package='odin_ros_driver_rev1',
            executable='post_process_node',
            name='postprocess',
            output='screen',
            parameters=[{}],
        ),
        Node(
            package='rviz2',
            executable='rviz2',
            name='odin_rviz',
            arguments=['-d', rviz_config],
            output='screen',
            condition=IfCondition(start_rviz),
        ),
    ]

    return LaunchDescription([
        DeclareLaunchArgument('device_sn', default_value=''),
        DeclareLaunchArgument('start_rviz', default_value='true'),
        DeclareLaunchArgument('rviz_config', default_value=default_rviz),
        DeclareLaunchArgument('image_width', default_value='0'),
        DeclareLaunchArgument('image_height', default_value='0'),
        DeclareLaunchArgument('image_fps', default_value='0'),
        DeclareLaunchArgument('image_format', default_value='mjpeg'),
        *nodes,
    ])
