#!/bin/bash
# Auto-generated by RoboMemo SFT Pipeline

python -m openpi.training.train \
  --config sft_output\demo_task\20260409_090118\configs\openpi_finetune.json \
  --output_dir sft_output\demo_task\20260409_090118\checkpoints \
  --experiment_name demo_task_20260409 \
  --bf16 \
  --lora_rank 32 \
  --lora_alpha 64.0
