#!/bin/bash
# Auto-generated by demo_screw_to_pi05_sft.py

python -m openpi.training.train \
  --config sft_output_screw2/configs/openpi_finetune.json \
  --output_dir checkpoints/openpi_screw_driving \
  --experiment_name roboforce_pi05_screw_v1 \
  --bf16 \
  --lora_rank 32 \
  --lora_alpha 64.0
